baseurl = "https://predatorian3.github.com/blog"
languageCode = "en-gb"
title = "Phil's Blog - Predatorian3"
theme = "hpstr"
pluralizelisttitles = false
PygmentsCodeFences = true
Paginate = 5
disqusShortname = "predatorian3-github-io"

[params]
	subtitle = "A blog of thoughts and learning"
	[params.author]
		name = "HPSTR"
		avatar = "/images/avatar.jpg"
		bio = "A guy who does a lot of thinking. Click for more!"
		github = "predatorian3/blog"
	[params.image]
	  feature = "/images/abstract-1.jpg"
	  credit = "dargadgetz"
	  creditlink = "http://www.dargadgetz.com/ios-7-abstract-wallpaper-pack-for-iphone-5-and-ipod-touch-retina/"
